### ISSUE TITLE
Error when browsers are installed to a custom directory

### ISSUE THREAD

**Issue by Flo-Slv** [dhruvmanila/telescope-bookmarks.nvim#20]
Hey !

My Brave browser  is installed with snap store on Ubuntu 22.04.

Bookmarks folder with snap is a bit different: `/home/{user}/snap/brave/current/.config/BraveSofware/Brave-Browser/Default/Bookmarks`

So I created a symlink to `/home/{user}/.config/BraveSoftware/Brave-Browser/Default/Bookmarks`

But I got this error: `bad argument #1 to 'decode' (string expected, got nil)`

![Screenshot from 2022-08-01 22-57-47](https://user-images.githubusercontent.com/11678456/182245502-83a5db47-4a55-4f4c-b106-463fa5f964d1.png)

![Screenshot from 2022-08-01 23-02-20](https://user-images.githubusercontent.com/11678456/182246114-2b02684c-d718-48fe-b549-1fa60dd65a4b.png)

Click on pictures for better quality xD

Did I miss something ?

Thanks !

**Comment by dhruvmanila** [comment]
related: #16 

For now, the simplest solution would be to resolve the symlink to the actual file on disk and read that instead. But, I would rather prefer to implement a long term solution of using XDG based directories along with user provided directories.

**Comment by dhruvmanila** [comment]
@Flo-Slv Hey, can you please update the extension to the latest commit and try again with `debug = true` config parameter? Provide the output.

**Comment by dhruvmanila** [comment]
Also, the way file is read in lua, it seems that the symlinks are resolved by it, so this problem shouldn't rise. There must be something else which is going on. Can you try this code by substituting the path to any symlink which points to a file containing some content?

```lua
local path = '/path/to/symlink'

local file, err = io.open(path, 'r')
if not file then
  return print(err)
end

local content = file:read '*a'
file:close()
print(content)
```

**Comment by Flo-Slv** [comment]
I just updated plugins with :PackerSync and now it's working ! Thanks !

I don't really know what's happened... you are right, with symlinks it's working great.

But I still have an issue but with... firefox now
```sh
defs.lua:31: libsqlite3.so cannot open shared object file No such file or directory
```

Here is the screenshot
![Screenshot from 2022-08-07 02-04-12](https://user-images.githubusercontent.com/11678456/183269639-dae1dc2b-faa1-471d-9d0b-6b3397d59c10.png)

Do I need to create an symlink too ? since in Ubuntu 22.04, Firefox is installed via snapstore

**Comment by dhruvmanila** [comment]
This would probably be because the dependencies weren't installed correctly, I'm not really sure. Can you look at https://github.com/kkharji/sqlite.lua and install it as mentioned in it's README with all the C dependencies? If not, this issue needs to be reported in that repository.

**Comment by Flo-Slv** [comment]
I thought only `tami5/sqlite.lua` was required. My bad, sorry !

So I installed `kkharji/sqlite.lua` too and give me a new error

```sh
defs.lua:683: sqlite.lua counldn't connect to sql database. ERR: unable to open database file 
```

Do I need to configure something else with sqlite3 ? Thanks 🙏🏼

**Comment by dhruvmanila** [comment]
They both are the same repository, the username was changed.

> since in Ubuntu 22.04, Firefox is installed via snapstore

Ah, yes. This is the problem. I think the extension should've errored before trying to open the database file as I'm getting the profile information from the `profiles.ini` file stored in the default Firefox config directory.

Can you check if the config directory is present? Location:

https://github.com/dhruvmanila/telescope-bookmarks.nvim/blob/0368bc390b25329f86b2a1bc83fa621ce921d7c6/lua/telescope/_extensions/bookmarks/firefox.lua#L12-L16

Also, sorry to ask you again, but please update the extension and share the output. I can reproduce the message on my system only if there is a profile directory but the database file is absent.

**Comment by Flo-Slv** [comment]
Thanks for your fast reply !

Here is the debug output

`Firefox bookmarks database file is not present in the profile director: /home/floslv/.mozilla/firefox/06lhu944.default/places.sqlite`

So I confirm I have a folder called `/home/floslv/.mozilla/firefox/`

```sh
ls /home/floslv/.mozilla/firefox/

06lhu944.default   0ojxz66h.default-release  'Crash Reports'   installs.ini  'Pending Pings'   profiles.ini
```

Here is my profile.ini
```sh
[Install4F96D1932A9F858E]
Default=0ojxz66h.default-release
Locked=1

[Profile1]
Name=default
IsRelative=1
Path=06lhu944.default
Default=1

[Profile0]
Name=default-release
IsRelative=1
Path=0ojxz66h.default-release

[General]
StartWithLastProfile=1
Version=2
```

Inside `06lhu944.default` folder, there is only one file `times.json`.

There is no `places.sqlite`

Inside `0ojxz66h.default-release`, there is `places.sqlite` but it's not my bookmarks, only default ones.

When I search on my files system for `places.sqlite`, the only return it's for `0ojxz66h.default-release`, nothing for `06lhu944.default`....

**Comment by Flo-Slv** [comment]
I found where my Firefox bookmarks are stored
`/home/floslv/snap/firefox/common/.mozilla/firefox/0ojxz66h.default-release/places.sqlite`

I just did a symlink from here to `/home/floslv/.mozilla/firefox/06lhu944.default/`

It's working like a charm now !

**Comment by dhruvmanila** [comment]
> It's working like a charm now !

Good to know that! I think there should be a better solution to this problem.

Continuing the discussion in #16 (or a new issue?)
